/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.bytequay.app.repository;

import com.bytequay.app.domain.TaskCheckpoint;

import java.util.List;
import java.util.Optional;

/**
 * Persistence interface for {@link TaskCheckpoint} rows.
 *
 * <p>The store is intentionally narrow — it only knows how to
 * read/write checkpoints. The CheckpointScheduler / Summariser
 * (Slice D) layer policy on top: when to generate, which window
 * to summarise, when to supersede the Overall row.
 *
 * <p>Two key invariants the store helps enforce by giving callers
 * convenient atomic primitives:
 * <ul>
 *   <li>Per-segment {@code seq} is unique per task and assigned
 *       sequentially. {@link #nextSegmentSeq} returns the value
 *       the next insert should use.</li>
 *   <li>At most one active Overall row per task. {@link
 *       #replaceOverall} swaps the current Overall in one transaction
 *       — stamps the previous row's {@code supersededAt} and writes
 *       the new one so a concurrent reader never sees zero or two
 *       active Overalls.</li>
 * </ul>
 */
public interface TaskCheckpointStore
{
    /** Insert a per-segment checkpoint. Callers compute {@code seq}
     *  via {@link #nextSegmentSeq}; the store doesn't double-check
     *  uniqueness, so two racing inserts will collide on the unique
     *  constraint (the scheduler serialises per task to avoid this). */
    void saveSegment(TaskCheckpoint segment);

    /** Atomic Overall swap: stamp any currently-active Overall as
     *  superseded and persist {@code next}. Use this rather than
     *  two separate writes so a reader can't briefly observe two
     *  active Overalls. */
    void replaceOverall(String taskId, TaskCheckpoint next);

    /** Every active checkpoint for the task (Overall + per-segment).
     *  Overall first, then segments by descending {@code seq} so the
     *  rail can render newest-segment-on-top without sorting. */
    List<TaskCheckpoint> listActive(String taskId);

    /** Single checkpoint by id — used by {@code GET
     *  /api/tasks/{id}/checkpoints/{id}} and by the cross-task seed
     *  loader when a specific checkpoint was picked. */
    Optional<TaskCheckpoint> findById(String id);

    /** Currently-active Overall row, or empty when none exists yet
     *  (the task hasn't crossed the threshold for its first segment). */
    Optional<TaskCheckpoint> findActiveOverall(String taskId);

    /** Most recent per-segment checkpoint, or empty when the task has
     *  no segments yet. The scheduler uses this to know where the
     *  next segment should start ({@code lastMsgSeq + 1}). */
    Optional<TaskCheckpoint> findLastSegment(String taskId);

    /** Next sequential {@code seq} to assign to a per-segment row —
     *  {@code 1} for the first segment, {@code maxSegmentSeq + 1}
     *  thereafter. Overall always uses {@code seq=0}, so this never
     *  returns 0. */
    long nextSegmentSeq(String taskId);

    /** Hard delete — only allowed for per-segment rows. Overall rows
     *  are regenerated by the scheduler and shouldn't be deleted
     *  manually; the API surface enforces that. */
    void deleteSegment(String id);
}
