/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.bytequay.app.repository;

import com.bytequay.app.domain.ThreadCheckpoint;

import java.util.List;
import java.util.Optional;

/**
 * Persistence interface for {@link ThreadCheckpoint} rows.
 *
 * <p>The store is intentionally narrow — it only knows how to
 * read/write checkpoints. The CheckpointScheduler / Summariser
 * (Slice D) layer policy on top: when to generate, which window
 * to summarise, when to supersede the Overall row.
 *
 * <p>Two key invariants the store helps enforce by giving callers
 * convenient atomic primitives:
 * <ul>
 *   <li>Per-segment {@code seq} is unique per thread and assigned
 *       sequentially. {@link #nextSegmentSeq} returns the value
 *       the next insert should use.</li>
 *   <li>At most one active Overall row per thread. {@link
 *       #replaceOverall} swaps the current Overall in one transaction
 *       — stamps the previous row's {@code supersededAt} and writes
 *       the new one so a concurrent reader never sees zero or two
 *       active Overalls.</li>
 * </ul>
 */
public interface ThreadCheckpointStore
{
    /** Insert a per-segment checkpoint. Callers compute {@code seq}
     *  via {@link #nextSegmentSeq}; the store doesn't double-check
     *  uniqueness, so two racing inserts will collide on the unique
     *  constraint (the scheduler serialises per thread to avoid this). */
    void saveSegment(ThreadCheckpoint segment);

    /** Insert a per-segment checkpoint scoped to one Task. Same as
     *  {@link #saveSegment} but stamps the new {@code task_id} column
     *  so this row belongs to the named Task's slice of the thread.
     *  Used by the Task-tier of the memory hierarchy described in
     *  the model doc; pre-existing Thread-only callers continue to
     *  use {@link #saveSegment} which leaves {@code task_id} null. */
    void saveSegmentForTask(String taskId, ThreadCheckpoint segment);

    /** Per-Task active checkpoints, newest-{@code seq} first. Empty
     *  when the task has not produced any checkpoints yet. */
    List<ThreadCheckpoint> listActiveForTask(String taskId);

    /** Atomic Overall swap: stamp any currently-active Overall as
     *  superseded and persist {@code next}. Use this rather than
     *  two separate writes so a reader can't briefly observe two
     *  active Overalls. */
    void replaceOverall(String threadId, ThreadCheckpoint next);

    /** Every active checkpoint for the thread (Overall + per-segment).
     *  Overall first, then segments by descending {@code seq} so the
     *  rail can render newest-segment-on-top without sorting. */
    List<ThreadCheckpoint> listActive(String threadId);

    /** Single checkpoint by id — used by {@code GET
     *  /api/threads/{id}/checkpoints/{id}} and by the cross-thread seed
     *  loader when a specific checkpoint was picked. */
    Optional<ThreadCheckpoint> findById(String id);

    /** Currently-active Overall row, or empty when none exists yet
     *  (the thread hasn't crossed the threshold for its first segment). */
    Optional<ThreadCheckpoint> findActiveOverall(String threadId);

    /** Most recent per-segment checkpoint, or empty when the thread has
     *  no segments yet. The scheduler uses this to know where the
     *  next segment should start ({@code lastMsgSeq + 1}). */
    Optional<ThreadCheckpoint> findLastSegment(String threadId);

    /** Next sequential {@code seq} to assign to a per-segment row —
     *  {@code 1} for the first segment, {@code maxSegmentSeq + 1}
     *  thereafter. Overall always uses {@code seq=0}, so this never
     *  returns 0. */
    long nextSegmentSeq(String threadId);

    /** Hard delete — only allowed for per-segment rows. Overall rows
     *  are regenerated by the scheduler and shouldn't be deleted
     *  manually; the API surface enforces that. */
    void deleteSegment(String id);
}
