-- Force a refresh of every cached repo_meta row so the parent_*
-- columns added in V46 get populated for existing fork repos
-- without waiting for the 1-hour TTL.
--
-- We can't gate on `parent_owner IS NULL` like the avatar backfill
-- did for `owner_avatar_url`, because GitHub legitimately returns
-- null parent for non-forks. Instead, push every row's synced_at to
-- the epoch so RepoService.getRepoMeta sees it as stale on the next
-- read; the existing stale-while-revalidate path serves the cached
-- (parent-less) row immediately and kicks off a background refresh
-- that fills in parent_owner / parent_repo / parent_default_branch.
UPDATE repo_meta SET synced_at = '1970-01-01T00:00:00Z';
